using System.Text.Json.Serialization;

namespace TestApp.Models
{
    public sealed class PurchaseLineModel
    {
        [JsonPropertyName("@odata.etag")]
        public string OdataEtag { get; set; }
        public string DocumentType { get; set; }
        public long DocumentNo { get; set; }
        public long LineNo { get; set; }
        public long BuyFromVendorNo { get; set; }
        public string Type { get; set; }
        public string No { get; set; }
        public string LocationCode { get; set; }
        public string PostingGroup { get; set; }
        public DateTime ExpectedReceiptDate { get; set; }
        public string Description { get; set; }
        public string Description2 { get; set; }
        public string UnitOfMeasure { get; set; }
        public long Quantity { get; set; }
        public long OutstandingQuantity { get; set; }
        public long QtyToInvoice { get; set; }
        public long QtyToReceive { get; set; }
        public double DirectUnitCost { get; set; }
        public double UnitCostLcy { get; set; }
        public long Vat { get; set; }
        public long LineDiscount { get; set; }
        public long LineDiscountAmount { get; set; }
        public long Amount { get; set; }
        public long AmountIncludingVat { get; set; }
        public double UnitPriceLcy { get; set; }
        public bool AllowInvoiceDisc { get; set; }
        public double GrossWeight { get; set; }
        public double NetWeight { get; set; }
        public long UnitsPerParcel { get; set; }
        public double UnitVolume { get; set; }
        public long ApplToItemEntry { get; set; }
        public string ShortcutDimension1Code { get; set; }
        public string ShortcutDimension2Code { get; set; }
        public string JobNo { get; set; }
        public long IndirectCost { get; set; }
        public bool RecalculateInvoiceDisc { get; set; }
        public long OutstandingAmount { get; set; }
        public long QtyRcdNotInvoiced { get; set; }
        public long AmtRcdNotInvoiced { get; set; }
        public long QuantityReceived { get; set; }
        public long QuantityInvoiced { get; set; }
        public string ReceiptNo { get; set; }
        public long ReceiptLineNo { get; set; }
        public string OrderNo { get; set; }
        public long OrderLineNo { get; set; }
        public long Profit { get; set; }
        public long PayToVendorNo { get; set; }
        public long InvDiscountAmount { get; set; }
        public string VendorItemNo { get; set; }
        public string SalesOrderNo { get; set; }
        public long SalesOrderLineNo { get; set; }
        public bool DropShipment { get; set; }
        public string GenBusPostingGroup { get; set; }
        public string GenProdPostingGroup { get; set; }
        public string VatCalculationType { get; set; }
        public string TransactionType { get; set; }
        public string TransportMethod { get; set; }
        public long AttachedToLineNo { get; set; }
        public string EntryPoint { get; set; }
        public string Area { get; set; }
        public string TransactionSpecification { get; set; }
        public string TaxAreaCode { get; set; }
        public bool TaxLiable { get; set; }
        public string TaxGroupCode { get; set; }
        public bool UseTax { get; set; }
        public string VatBusPostingGroup { get; set; }
        public string VatProdPostingGroup { get; set; }
        public string CurrencyCode { get; set; }
        public long OutstandingAmountLcy { get; set; }
        public long AmtRcdNotInvoicedLcy { get; set; }
        public long ReservedQuantity { get; set; }
        public string BlanketOrderNo { get; set; }
        public long BlanketOrderLineNo { get; set; }
        public long VatBaseAmount { get; set; }
        public double UnitCost { get; set; }
        public bool SystemCreatedEntry { get; set; }
        public long LineAmount { get; set; }
        public long VatDifference { get; set; }
        public long InvDiscAmountToInvoice { get; set; }
        public string VatIdentifier { get; set; }
        public string IcPartnerRefType { get; set; }
        public string IcPartnerReference { get; set; }
        public long Prepayment { get; set; }
        public long PrepmtLineAmount { get; set; }
        public long PrepmtAmtInv { get; set; }
        public long PrepmtAmtInclVat { get; set; }
        public long PrepaymentAmount { get; set; }
        public long PrepmtVatBaseAmt { get; set; }
        public long PrepaymentVat { get; set; }
        public string PrepmtVatCalcType { get; set; }
        public string PrepaymentVatIdentifier { get; set; }
        public string PrepaymentTaxAreaCode { get; set; }
        public bool PrepaymentTaxLiable { get; set; }
        public string PrepaymentTaxGroupCode { get; set; }
        public long PrepmtAmtToDeduct { get; set; }
        public long PrepmtAmtDeducted { get; set; }
        public bool PrepaymentLine { get; set; }
        public long PrepmtAmountInvInclVat { get; set; }
        public long PrepmtAmountInvLcy { get; set; }
        public string IcPartnerCode { get; set; }
        public long PrepmtVatAmountInvLcy { get; set; }
        public long PrepaymentVatDifference { get; set; }
        public long PrepmtVatDiffToDeduct { get; set; }
        public long PrepmtVatDiffDeducted { get; set; }
        public string IcItemReferenceNo { get; set; }
        public long OutstandingAmtExVatlcy { get; set; }
        public long ARcdNotInvExVatlcy { get; set; }
        public long PmtDiscountAmount { get; set; }
        public long PrepmtPmtDiscountAmount { get; set; }
        public long DimensionSetId { get; set; }
        public string JobTaskNo { get; set; }
        public string JobLineType { get; set; }
        public long JobUnitPrice { get; set; }
        public long JobTotalPrice { get; set; }
        public long JobLineAmount { get; set; }
        public long JobLineDiscountAmount { get; set; }
        public long JobLineDiscount { get; set; }
        public long JobUnitPriceLcy { get; set; }
        public long JobTotalPriceLcy { get; set; }
        public long JobLineAmountLcy { get; set; }
        public long JobLineDiscAmountLcy { get; set; }
        public long JobCurrencyFactor { get; set; }
        public string JobCurrencyCode { get; set; }
        public long JobPlanningLineNo { get; set; }
        public long JobRemainingQty { get; set; }
        public long JobRemainingQtyBase { get; set; }
        public string DeferralCode { get; set; }
        public DateTime ReturnsDeferralStartDate { get; set; }
        public string ProdOrderNo { get; set; }
        public string VariantCode { get; set; }
        public string BinCode { get; set; }
        public long QtyPerUnitOfMeasure { get; set; }
        public long QtyRoundingPrecision { get; set; }
        public long QtyRoundingPrecisionBase { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public long QuantityBase { get; set; }
        public long OutstandingQtyBase { get; set; }
        public long QtyToInvoiceBase { get; set; }
        public long QtyToReceiveBase { get; set; }
        public long QtyRcdNotInvoicedBase { get; set; }
        public long QtyReceivedBase { get; set; }
        public long QtyInvoicedBase { get; set; }
        public long ReservedQtyBase { get; set; }
        public DateTime FaPostingDate { get; set; }
        public string FaPostingType { get; set; }
        public string DepreciationBookCode { get; set; }
        public long SalvageValue { get; set; }
        public bool DeprUntilFaPostingDate { get; set; }
        public bool DeprAcquisitionCost { get; set; }
        public string MaintenanceCode { get; set; }
        public string InsuranceNo { get; set; }
        public string BudgetedFaNo { get; set; }
        public string DuplicateInDepreciationBook { get; set; }
        public bool UseDuplicationList { get; set; }
        public string ResponsibilityCenter { get; set; }
        public string ItemCategoryCode { get; set; }
        public bool Nonstock { get; set; }
        public string PurchasingCode { get; set; }
        public bool SpecialOrder { get; set; }
        public string SpecialOrderSalesNo { get; set; }
        public long SpecialOrderSalesLineNo { get; set; }
        public string ItemReferenceNo { get; set; }
        public string ItemReferenceUnitOfMeasure { get; set; }
        public string ItemReferenceType { get; set; }
        public string ItemReferenceTypeNo { get; set; }
        public long WhseOutstandingQtyBase { get; set; }
        public bool CompletelyReceived { get; set; }
        public DateTime RequestedReceiptDate { get; set; }
        public DateTime PromisedReceiptDate { get; set; }
        public string LeadTimeCalculation { get; set; }
        public string InboundWhseHandlingTime { get; set; }
        public DateTime PlannedReceiptDate { get; set; }
        public DateTime OrderDate { get; set; }
        public bool AllowItemChargeAssignment { get; set; }
        public long QtyToAssign { get; set; }
        public long QtyAssigned { get; set; }
        public long ReturnQtyToShip { get; set; }
        public long ReturnQtyToShipBase { get; set; }
        public long ReturnQtyShippedNotInvd { get; set; }
        public long RetQtyShpdNotInvdBase { get; set; }
        public long ReturnShpdNotInvd { get; set; }
        public long ReturnShpdNotInvdLcy { get; set; }
        public long ReturnQtyShipped { get; set; }
        public long ReturnQtyShippedBase { get; set; }
        public long ItemChargeQtyToHandle { get; set; }
        public string ReturnShipmentNo { get; set; }
        public long ReturnShipmentLineNo { get; set; }
        public string ReturnReasonCode { get; set; }
        public string Subtype { get; set; }
        public bool CopiedFromPostedDoc { get; set; }
        public string PriceCalculationMethod { get; set; }
        public long AttachedDocCount { get; set; }
        public long OverReceiptQuantity { get; set; }
        public string OverReceiptCode { get; set; }
        public string OverReceiptApprovalStatus { get; set; }
        public bool ReverseChargeItem { get; set; }
        public string RoutingNo { get; set; }
        public string OperationNo { get; set; }
        public string WorkCenterNo { get; set; }
        public bool Finished { get; set; }
        public long ProdOrderLineNo { get; set; }
        public long OverheadRate { get; set; }
        public bool MpsOrder { get; set; }
        public string PlanningFlexibility { get; set; }
        public string SafetyLeadTime { get; set; }
        public long RoutingReferenceNo { get; set; }
        public DateTime SystemCreatedAt { get; set; }
        public string SystemCreatedBy { get; set; }
        public string SystemId { get; set; }
        public DateTime SystemModifiedAt { get; set; }
        public string SystemModifiedBy { get; set; }
    }
}
