using System.Text.Json.Serialization;
namespace TestApp.Models;

public sealed class PurchaseHeaderModel
{
    [JsonPropertyName("@odata.etag")]
    public string OdataEtag { get; set; }
    public string DocumentType { get; set; }     
    public long No { get; set; }
    public string BuyFromVendorNo { get; set; }
    public string PayToVendorNo { get; set; }
    public string PayToName { get; set; }
    public string PayToName2 { get; set; }
    public string PayToAddress { get; set; }
    public string PayToAddress2 { get; set; }
    public string PayToCity { get; set; }
    public string PayToContact { get; set; }
    public string YourReference { get; set; }
    public string ShipToCode { get; set; }    
    public string ShipToName { get; set; }
    public string ShipToName2 { get; set; }
    public string ShipToAddress { get; set; }
    public string ShipToAddress2 { get; set; }
    public string ShipToCity { get; set; }
    public string ShipToContact { get; set; }
    public DateTime OrderDate { get; set; }
    public DateTime PostingDate { get; set; }
    public DateTime ExpectedReceiptDate { get; set; }
    public string PostingDescription { get; set; }
    public string PaymentTermsCode { get; set; }
    public DateTime DueDate { get; set; }
    public long PaymentDiscount { get; set; }
    public DateTime PmtDiscountDate { get; set; }
    public string ShipmentMethodCode { get; set; }
    public string LocationCode { get; set; }
    public string ShortcutDimension1Code { get; set; }
    public string ShortcutDimension2Code { get; set; }
    public string VendorPostingGroup { get; set; }
    public string CurrencyCode { get; set; }
    public double CurrencyFactor { get; set; }
    public bool PricesIncludingVat { get; set; }
    public string InvoiceDiscCode { get; set; }
    public string LanguageCode { get; set; }
    public string PurchaserCode { get; set; }
    public string OrderClass { get; set; }
    public bool Comment { get; set; }
    public long NoPrinted { get; set; }
    public string OnHold { get; set; }
    public string AppliesToDocType { get; set; }
    public string AppliesToDocNo { get; set; }
    public string BalAccountNo { get; set; }
    public bool RecalculateInvoiceDisc { get; set; }
    public bool Receive { get; set; }
    public bool Invoice { get; set; }
    public bool PrintPostedDocuments { get; set; }
    public double Amount { get; set; }
    public double AmountIncludingVat { get; set; }
    public string ReceivingNo { get; set; }
    public string PostingNo { get; set; }
    public string LastReceivingNo { get; set; }
    public string LastPostingNo { get; set; }
    public string VendorOrderNo { get; set; }
    public string VendorShipmentNo { get; set; }
    public string VendorInvoiceNo { get; set; }
    public string VendorCrMemoNo { get; set; }
    public string VatRegistrationNo { get; set; }
    public string SellToCustomerNo { get; set; }
    public string ReasonCode { get; set; }
    public string GenBusPostingGroup { get; set; }
    public string TransactionType { get; set; }
    public string TransportMethod { get; set; }
    public string VatCountryRegionCode { get; set; }
    public string BuyFromVendorName { get; set; }
    public string BuyFromVendorName2 { get; set; }
    public string BuyFromAddress { get; set; }
    public string BuyFromAddress2 { get; set; }
    public string BuyFromCity { get; set; }
    public string BuyFromContact { get; set; }
    public string PayToPostCode { get; set; }
    public string PayToCounty { get; set; }
    public string PayToCountryRegionCode { get; set; }
    public string BuyFromPostCode { get; set; }
    public string BuyFromCounty { get; set; }
    public string BuyFromCountryRegionCode { get; set; }
    public string ShipToPostCode { get; set; }
    public string ShipToCounty { get; set; }
    public string ShipToCountryRegionCode { get; set; }
    public string BalAccountType { get; set; }
    public string OrderAddressCode { get; set; }
    public string EntryPoint { get; set; }
    public bool Correction { get; set; }
    public DateTime DocumentDate { get; set; }
    public string Area { get; set; }
    public string TransactionSpecification { get; set; }
    public string PaymentMethodCode { get; set; }
    public string NoSeries { get; set; }
    public string PostingNoSeries { get; set; }
    public string ReceivingNoSeries { get; set; }
    public string TaxAreaCode { get; set; }
    public bool TaxLiable { get; set; }
    public string VatBusPostingGroup { get; set; }
    public string AppliesToId { get; set; }
    public long VatBaseDiscount { get; set; }
    public string Status { get; set; }
    public string InvoiceDiscountCalculation { get; set; }
    public long InvoiceDiscountValue { get; set; }
    public bool SendIcDocument { get; set; }
    public string IcStatus { get; set; }
    public string BuyFromIcPartnerCode { get; set; }
    public string PayToIcPartnerCode { get; set; }
    public string IcDirection { get; set; }
    public string PrepaymentNo { get; set; }
    public string LastPrepaymentNo { get; set; }
    public string PrepmtCrMemoNo { get; set; }
    public string LastPrepmtCrMemoNo { get; set; }
    public long Prepayment { get; set; }
    public string PrepaymentNoSeries { get; set; }
    public bool CompressPrepayment { get; set; }
    public DateTime PrepaymentDueDate { get; set; }
    public string PrepmtCrMemoNoSeries { get; set; }
    public string PrepmtPostingDescription { get; set; }
    public DateTime PrepmtPmtDiscountDate { get; set; }
    public string PrepmtPaymentTermsCode { get; set; }
    public long PrepmtPaymentDiscount { get; set; }
    public string QuoteNo { get; set; }
    public string JobQueueStatus { get; set; }
    public string JobQueueEntryId { get; set; }
    public long IncomingDocumentEntryNo { get; set; }
    public string CreditorNo { get; set; }
    public string PaymentReference { get; set; }
    public string JournalTemplName { get; set; }
    public DateTime VatReportingDate { get; set; }
    public long ARcdNotInvExVatlcy { get; set; }
    public long AmtRcdNotInvoicedLcy { get; set; }
    public long DimensionSetId { get; set; }
    public string RemitToCode { get; set; }
    public long InvoiceDiscountAmount { get; set; }
    public long NoOfArchivedVersions { get; set; }
    public long DocNoOccurrence { get; set; }
    public string CampaignNo { get; set; }
    public string BuyFromContactNo { get; set; }
    public string PayToContactNo { get; set; }
    public string ResponsibilityCenter { get; set; }
    public bool PartiallyInvoiced { get; set; }
    public bool CompletelyReceived { get; set; }
    public long PostingFromWhseRef { get; set; }
    public DateTime RequestedReceiptDate { get; set; }
    public DateTime PromisedReceiptDate { get; set; }        
    public string LeadTimeCalculation { get; set; }
    public string InboundWhseHandlingTime { get; set; }
    public string VendorAuthorizationNo { get; set; }
    public string ReturnShipmentNo { get; set; }
    public string ReturnShipmentNoSeries { get; set; }
    public bool Ship { get; set; }
    public string LastReturnShipmentNo { get; set; }
    public string PriceCalculationMethod { get; set; }
    public string AssignedUserId { get; set; }
    public long PendingApprovals { get; set; }
    public DateTime InvoiceReceiptDate { get; set; }
    public DateTime SystemCreatedAt { get; set; }
    public string SystemCreatedBy { get; set; }
    public string SystemId { get; set; }
    public DateTime SystemModifiedAt { get; set; }
    public string SystemModifiedBy { get; set; }
}
